name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  mqtt_client: ^10.5.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
